[IndexFiltering]
Shopify/polaris-react pull request #10000
Opened 2023-08-10 14:57 UTC by zakwarsame

### WHY are these changes introduced?

Fixes https://github.com/Shopify/web/pull/100983

- Currently when navigating to a given index table with the  query included in the URL, the input field will contain the value but will not be focused
- Since only indexes containing queries have the state of `mode` as Filtering, it makes sense to initialize with `mode`. This way when the URL includes a query, the input field is focused without accessibility trade-offs.

### WHAT is this pull request doing?

- This PR sets the initial focus of the input fields to true when `IndexFiltersMode` is `Filtering`.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

- [Spin URL](https://admin.web.df.zakaria-warsame.us.spin.dev/store/shop1/products?query=aero) with query
  - Ensure the input is focus when you go to the page or refresh with the query included

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
~ - [ ] Updated the component's `README.md` with documentation changes~ 
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-08-10 14:57 UTC, zakwarsame commented
/snapit

2023-08-11 04:14 UTC, jesstelford requested changes
Thanks for the contribution @zakwarsame!

I'm not sure of the accessibility implications of defaulting focus to `true`; wouldn't this steal the focus for every page with an IndexTable, jumping the user directly to the search field? How would a screen reader user handle that?

Relatedly; how would we handle the case when there's more than one `<IndexTable>` on the page? Which one should receive focus?

Finally, should this also trigger the `onQueryFocus()` callback?

An alternate solution might be a `defaultFocus` prop which is passed into `useToggle(defaultFocus)` + a `useEffect()` which calls `onQueryFocus()` once on mount if `defaultFocus == true`. This leaves the auto-focusing up to the callsite, allowing for more flexibility.

2023-08-11 17:16 UTC, zakwarsame commented
@jesstelford I appreciate the feedback!

> I'm not sure of the accessibility implications of defaulting focus to true; wouldn't this steal the focus for every page with an IndexTable, jumping the user directly to the search field? How would a screen reader user handle that?

I think that's a fair point but also, the [useOnValueChange](https://github.com/Shopify/polaris/blob/6c1633cbf8823e3d55c51f1f8531ca6375d7f3f5/polaris-react/src/components/IndexFilters/IndexFilters.tsx#L150) hook already runs on every render except the first. It checks the current mode of the `IndexFilters` and sets the focus when the mode is `Filtering`. From an a11y perspective, this hook should protect the focus on tables that aren't actively filtering.

I understand why blindly setting it to `true` isn't ideal though. Instead of defaulting to false on the first render, I think it makes sense to either: 

a. Check if the mode is set to `Filtering` and set that as the initial value i.e `useToggle(mode === IndexFiltersMode.Filtering);` or
b. Add a `useEffect` that runs once throughout the lifecycle of the component i.e
```
useEffect(() => {
  handleModeChange(mode);
}, []);
```


> Relatedly; how would we handle the case when there's more than one <IndexTable> on the page? Which one should receive focus?

With the above solution in mind, whichever has the current `mode` set to `Filtering`.

> Finally, should this also trigger the onQueryFocus() callback?

Currently, `onQueryFocus()` is independent from the `mode` logic. I think this is because `handleQueryFocus` is meant to handle it separately. If we want the `onQueryFocus()` to run each time the `mode` logic is run, we should add it inside the callback being passed to `useOnValueChange` which will automatically run it.

> An alternate solution might be a defaultFocus prop which is passed into useToggle(defaultFocus) + a useEffect() which calls onQueryFocus() once on mount if defaultFocus == true. This leaves the auto-focusing up to the callsite, allowing for more flexibility.

I think this makes sense. Although, it might be a little redundant to add the prop if the intention is to simply ensure the `mode` is in `Filtering` state. Let me know what you think of the above solutions, otherwise, I'll add the prop.

2023-08-30 22:00 UTC, zakwarsame commented
/snapit

2023-09-05 15:42 UTC, zakwarsame commented
Closing in favor of https://github.com/Shopify/polaris/pull/10284

2023-09-05 15:42 UTC, closed without merging