[polaris.shopify.com] Add new `/design/icons` design guidance
Shopify/polaris-react pull request #10672
Opened 2023-09-25 21:54 UTC by yurm04

### WHY are these changes introduced?

Fixes #10694  

### WHAT is this pull request doing?

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2023-09-25 21:59 UTC, yurm04 commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +description: Icons enhance an experience by providing intuitive and efficient navigation, conveying information concisely, and making it more visually appealing.
@zecarlostorre @tjonx are we using ledes in the L3 pages? if so we'll need un updated lede/description here.

Also need the keywords for this page

2023-09-25 21:59 UTC, yurm04 commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +        ![](/images/design/icons/icons-overview-universal-1@2x.png)
need the rest of the assets for this `/design/icons` guidance, just been reusing the ones from overview

2023-09-27 15:15 UTC, yurm04 commented on polaris.shopify.com/src/components/Markdown/components/DirectiveCard/index.tsx
> +  status?: DirectiveStatus;
Sometimes these cards should not have a pill indicating status (just a plain card)

2023-09-28 18:16 UTC, zecarlostorre requested changes
Thank you Yuraima, apologies for the delay.
I left comments in line where I found strings with the wrong text.

Besides that:
1. The icons missing here are:
EditMinor - Creating icons
PaintBrushMajor - Using icons
<img width="403" alt="Screenshot 2023-09-28 at 18 51 03" src="https://github.com/Shopify/polaris/assets/55551051/5cc409a2-485f-4979-99b7-e16e1b50a565">

2. Most of my images show up cropped because they're 4:3, can we adjust that? <img width="930" alt="Screenshot 2023-09-28 at 18 51 15" src="https://github.com/Shopify/polaris/assets/55551051/082e38d5-5ce0-4910-8b78-d6a064225e1e">

3. These are the wrong visuals. The visuals in this section are numbered, and the name is:
icons-creating-filled-vs-outline-...
<img width="925" alt="Screenshot 2023-09-28 at 18 51 27" src="https://github.com/Shopify/polaris/assets/55551051/54a206e9-f246-4344-9224-9cc4888ee986">

4. Can we force these to align?
<img width="933" alt="Screenshot 2023-09-28 at 18 54 08" src="https://github.com/Shopify/polaris/assets/55551051/41e4dec1-0970-4788-a445-651a016e70a1">

So they look like this instead:
<img width="902" alt="Screenshot 2023-09-28 at 19 11 39" src="https://github.com/Shopify/polaris/assets/55551051/e584bddf-a38d-4bba-9964-831f71077fe0">

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/index.md
> +        Draw simple objects that are easy to identify.
Replace this string with:
Embellish the icon with unnecessary details.

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +    <DirectiveCard status="Tip">
Can you remove the "tip" badge from the first 4 examples in this page?

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +      Icons are two-dimensional, and objects face forward.
Replace this string with:
Use perspective and 3D objects.

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +        Filled icons should align closely to their outline pairs. They don’t need to be a pixel perfect match, but the transition from one to the other must feel smooth.
Replace this string with:
Icons are made out of contiguous shapes. Ideally one, but it’s possible to go up to three, when required for clarity.

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/using-icons.md
> +            Use icons consistently once a meaning is assigned to them.
Replace this string with:
Overuse icons. Redundant icons lead to visual clutter and increased cognitive load.

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/using-icons.md
> +        Use icons to replace text for common actions with universally understood icons.
Replace this string with:
Align icons vertically with accompanying typography.

2023-09-28 18:16 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/using-icons.md
> +        Use ambiguous icons without a text label, as that can lead to confusion and misinterpretation.
Replace this string with:
Resize icons. Resizing them will distort the relationship that was established with typography.

2023-09-28 18:20 UTC, zecarlostorre commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +description: Icons enhance an experience by providing intuitive and efficient navigation, conveying information concisely, and making it more visually appealing.
Keywords for this sections could be:
- Icons
- Icon Design
- User Interface Design
- Visual Navigation
- Consistent Icon Style
- Universally Recognized Symbols
- Icon Creation
- Icon Layout
- 2D Icons
- Icon Stroke Weight
- Filled Icons
- Outlined Icons
- Icon Navigation
- Iconography
- Icon Visual Weight
- Icon Design Guidelines
- Icon Use in Interface
- Icon and Typography
- Icon Size and Weight
- Icon Clarity
- Icon Meaning
- Icon Aesthetics
- Icon Functionality
- Icon Grid Alignment
- Icon Visual Harmony.

2023-10-03 14:28 UTC, yurm04 commented on polaris.shopify.com/content/design/icons/creating-icons.md
> +description: Icons enhance an experience by providing intuitive and efficient navigation, conveying information concisely, and making it more visually appealing.
thanks @zecarlostorre ! any updates for the description for this page?

Any updates for the Using Icons page?

2023-10-03 14:58 UTC, yurm04 commented
Hey @zecarlostorre 👋 

> Most of my images show up cropped because they're 4:3, can we adjust that?

> Can we force these to align?

Mind making two issues for these and add them to the backlog? These would need to be changes to the component that will affect all of the cards so we should fix separate to this PR

2023-10-03 21:20 UTC, merged