[VF][Polaris] Added dragAndDropOnly prop to DropZone
Shopify/polaris-react pull request #11610
Opened 2024-02-16 00:27 UTC by oksanashopify

New property `dragAndDropOnly` to Polaris [DropZone](https://polaris.shopify.com/components/selection-and-input/drop-zone)  will allow us to maintain consistent user experience in cases when we opting for a personalized Modal over the default File Dialog using `onClick` for both mouse and keyboard navigation.

### WHY are these changes introduced?

There are few places across the Admin and in Themes where, when user navigates using keyboard, two modals are getting opened and focus gets lost among them. Also new Variants card on PDP implements DropZone on confined space along with custom child activator which caused two interactive elements (DropZone `input` and custom `button`) get focused. With `dragAndDropOnly`  we can decide on consumer level whether we want to make DropZone `input` element keyboard accessible or delegate that role to child element which serves as the modal activator and provides accessibility and custom design features.

Resolves: https://github.com/Shopify/temp-project-mover-syfiawoo-20250331132715/issues/614

### WHAT is this pull request doing?

- Adds `dragAndDropOnly` to Polaris [DropZone](https://polaris.shopify.com/components/selection-and-input/drop-zone);
- Adds new Story "With Custom Modal And Drag And Drop Only":
<img width="1511" alt="image" src="https://github.com/Shopify/polaris/assets/104942025/e896adfb-0bdd-4de7-b43f-027baa2ed475">
 
- Adds new code example to polaris.shopify.com website
<img width="1201" alt="image" src="https://github.com/Shopify/polaris/assets/104942025/fbf5ebe5-3bd2-4308-af9d-a706f580ba79">

- Updates Keyboard support section on polaris.shopify.com website
 
![image](https://github.com/Shopify/polaris/assets/104942025/e6422e4d-b5c4-48ba-87f5-c0152c35b2fb)

 

### How to 🎩
[Admin Spin](https://admin.web.oa-web-test-restrictkeyboardaccess.oksana-azarova.us.spin.dev/store/shop1/products/1)
Draft web PR with snapshot [[Web][PDP]Added restrictKeyboardAccess to DropZone ](https://github.com/Shopify/web/pull/120196)
⚠️ if you testing this patch on your own spin, make sure to remove `tabIndex={-1}` in `ImageSelector/components/ImageModalActivator/ImageModalActivator.tsx` that was added as temporary fix.

Steps:

1. Go to PDP and make sure you have variants created
2. Try to upload variant or variants group image using keyboard navigation
3. Make sure DropZone is not keyboard accessible, only one modal gets opened and drop zone area gets focus once

Variants Card before:  https://screenshot.click/15-24-up4jx-vti9b.mp4
Variants Card after: https://screenshot.click/15-33-gesro-uk35s.mp4

[Themes Spin](https://admin.web.oa-web-test-restrictkeyboardaccess.oksana-azarova.us.spin.dev/store/shop1/themes/1/editor?section=template--185__image_banner) [`online-store-web` constellation] implements current snapshot

Steps:

1. Go to the Theme settings and Open to edit logo
2. Try to upload the logo using keyboard navigation
3. Make sure DropZone is not keyboard accessible and only one modal gets opened on on iteracting with a child activator

Theme settings before: https://screenshot.click/15-42-wjoxo-5r6gx.mp4
Theme settings after: https://screenshot.click/16-58-0wz5o-kelzu.mp4

Code example:

```
<DropZone
        type={ACCEPTED_FILE_TYPE}
        accept={ValidDropzoneImages}
        allowMultiple={false}
        onDropAccepted={handleOnDropAccepted}
        onDropRejected={handleOnDropRejected}
        onClick={handleOnClick}
        dragAndDropOnly
      >
        {children}
      </DropZone>
```

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#install-dependencies-and-build-workspaces)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

### 🎩 checklist

- [x] Tested a [snapshot](https://github.com/Shopify/polaris/blob/main/documentation/Releasing.md#-snapshot-releases)
- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2024-02-16 00:34 UTC, oksanashopify commented
/snapit

2024-02-16 00:43 UTC, oksanashopify commented
/snapit

2024-02-16 00:54 UTC, oksanashopify commented
/snapit

2024-02-16 01:24 UTC, oksanashopify commented
/snapit

2024-02-23 14:29 UTC, kyledurand requested changes
I think this prop might encourage bad accessibility habits, and potentially bad UX.

Dropzone is a form element and should perform a single task. Is this a case where the dropzone that's been implemented is trying to do too many things? 

I personally don't see the issue with your first examples where the screenreader announces the file upload option and then goes on to announce a different action of selecting images.

2024-02-26 18:01 UTC, oksanashopify commented
> I think this prop might encourage bad accessibility habits, and potentially bad UX.
> 
> Dropzone is a form element and should perform a single task. Is this a case where the dropzone that's been implemented is trying to do too many things?
> 
> I personally don't see the issue with your first examples where the screenreader announces the file upload option and then goes on to announce a different action of selecting images.

Thank you for your feedback @kyledurand! 
I would like to provide more real-life examples so maybe we can reconsider adding `restrictKeyboardAccess` or maybe we will come up with different solution.

1.  To: 
> I personally don't see the issue with your first examples where the screenreader announces the file upload option and then goes on to announce a different action of selecting images.

Re: 
Implementing `small-sized` [DropZone](https://polaris.shopify.com/components/selection-and-input/drop-zone) with `children` that  works as modal activator itself and along with custom callback that triggers open custom modal `onClick?`  -  focus moves between two interactive elements, so user has **_to tab twice_** in order to upload a file. Can we consider this as accessibility issue? CC: @svinkle ?
Moreover while we can provide all accessibility labels for custom `children` to convey to the visually impaired users the status of uploaded/not uploaded file + the purpose of file uploading ("Upload image for variants", for example), DropZone component does not allow us to do so and provides misleading area attributes that does not correspond the real state of file, for example when File is uploaded - DropZone says "Upload image: no file chosen". Video: https://screenshot.click/26-35-nmyhu-5pre5.mp4. (Misleading area attributes sound like a separate issue/concern that can be fixed for DropZone component).
To fix "double tab" for new Variants card we had to disable keyboard access for `children` activator, and lost access to its AREA attributes. Video from prod: https://screenshot.click/26-28-m7pr5-mdugn.mp4. (Additionally I think it introduces some confusion for developers as we disabling drag and drop functionality `onClick` using custom callback and at the same time had to restrict keyboard access to `children` activator to eliminate double tab)

2. To:

> Dropzone is a form element and should perform a single task. Is this a case where the dropzone that's been implemented is trying to do too many things?

Re: 
Implementing [DropZone](https://polaris.shopify.com/components/selection-and-input/drop-zone) with custom callback that triggers open custom modal `onClick?` already introduces accessibility issue:  when user navigates using keyboard and press Enter On DropZone - it would open two modals which seems to be already not great UX and also introduces difficulties for visually impaired users as focus moves from one modal to another even file is uploaded through the first opened modal.
      -  [sandbox](https://codesandbox.io/p/sandbox/gallant-swanson-p8q38w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsz5myaw00063b6kkxejkw3o%2522%252C%2522sizes%2522%253A%255B90%252C10%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsz5myaw00023b6kh43l1819%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsz5myaw00033b6k6qq0sm9t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsz5myaw00053b6kfy6cdlwh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.90044222218168%252C49.09955777781832%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsz5myaw00023b6kh43l1819%2522%253A%257B%2522id%2522%253A%2522clsz5myaw00023b6kh43l1819%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsz5myaw00053b6kfy6cdlwh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsz5myaw00043b6kx4fbeq93%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsz5myaw00053b6kfy6cdlwh%2522%252C%2522activeTabId%2522%253A%2522clsz5myaw00043b6kx4fbeq93%2522%257D%252C%2522clsz5myaw00033b6k6qq0sm9t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsz5myaw00033b6k6qq0sm9t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D);
      -  Admin theme settings: https://screenshot.click/15-42-wjoxo-5r6gx.mp4   

These issues were identified with help of Scott Vinkle (@svinkle) from #help-accessibility team when we were working on accessibility for image inline editing for new Variants Card.  Scott suggested that we shouldn't have a situation with opening two modals when user lands on image editing area and also suggested to apply area attributes to convey the status of uploaded image. Related Issue with discussions:  https://github.com/Shopify/web/issues/109222.
Moreover if we already applied open custom modal `onClick?` that means we want to use custom functionality to upload file, right? So visually impaired users still have all the tools to upload file. And users who can use mouse or a touchpad additionally can also drag and drop images. That's why disabling keyboard access for DropZone functionality is something that we considered for the new Variants card with @supervee.


So seems like in some cases we want to  disable keyboard access for DropZone functionality.  
Introducing `restrictKeyboardAccess` we can decide on consumer level whether we want to make DropZone functionality keyboard accessible. And if `restrictKeyboardAccess` is true - we can utilize all the accessibility features of 'children' element, as described in the following issue: https://github.com/Shopify/web/issues/109222. 

3. To:

> I think this prop might encourage bad accessibility habits, and potentially bad UX.

@kyledurand Could you please elaborate on concerns you outlined.  What exactly bad accessibility habits and potentially bad UX you can foresee here? Would you suggest alternative path for fixing issues outlined above? I also open for pairing session! Thank you!
 
 @supervee, @svinkle I will appreciate if you can share your thoughts at this matter. Maybe I'm missing something and  introducing `restrictKeyboardAccess` for DropZone encourages bad accessibility habits, and potentially bad UX and we should look for alternative ways? Thank you!

2024-02-27 18:45 UTC, kyledurand commented
> user has to tab twice in order to upload a file

This is the part I'm confused about. When testing this I noticed that it wasn't two tabs to upload. The first tab focused the dropzone input allowing file uploads. The second tab focused the select images modal, where the user can select from previously uploaded images, or upload new files. 

I might be missing something. Would also like to hear from others

2024-03-01 17:52 UTC, oksanashopify commented
> restrictKeyboardAccess
Thank you @kyledurand for taking a look! You might not see  two tabs to upload  image on your spin, because we disabled keyboard access to our custom child element in web. Here is a [draft PR](https://github.com/Shopify/web/pull/120196)  that reverts our temporary fix back and uses new `restrictKeyboardAccess`;

I also recorded a [video](https://share.descript.com/view/qnk8D97tkUm) showcasing places that would benefit from having a choice to disable keyboard access for the DropZone.

Please let me know if you have any other questions.

2024-03-05 02:53 UTC, oksanashopify commented
/snapit

2024-03-05 03:04 UTC, oksanashopify commented
/snapit

2024-03-05 15:57 UTC, oksanashopify commented
/snapit

2024-03-07 20:07 UTC, kyledurand commented on polaris-react/src/components/DropZone/DropZone.tsx
> +              tabIndex={onClick && dragAndDropOnly ? -1 : 0}
Since `onClick` is required for this to work I think we should leverage typescript and error if only `dragAndDropOnly` is provided.

2024-03-08 20:10 UTC, tatianau commented on .changeset/hip-rockets-yawn.md
> +Added dragAndDropOnly property for DropZone to determine if keyboard accessibility is enabled when using the component along with custom onClick for files uploading
```suggestion
Added `dragAndDropOnly` property for `DropZone` to determine if keyboard accessibility is enabled when using the component along with custom onClick for files uploading
```

2024-03-08 20:10 UTC, tatianau commented on polaris-react/src/components/DropZone/DropZone.stories.tsx
> +        accessibility and custom desight features.
Is this intentional?
```suggestion
        accessibility and custom features.
```

2024-03-08 20:10 UTC, tatianau commented on polaris-react/src/components/DropZone/DropZone.tsx
> +  /** Determines if keyboard accessibility is enabled when using the component along with custom onClick */
Can we be more specific about accessibility here? E.g. `determines if activator receives keyboard focus` or something along those lines?

2024-03-08 20:10 UTC, tatianau commented on polaris-react/src/components/DropZone/DropZone.tsx
> +  dragAndDropOnly,
Optional props should have a default value set

2024-03-08 20:10 UTC, tatianau commented on polaris-react/src/components/DropZone/DropZone.tsx
> +              tabIndex={onClick && dragAndDropOnly ? -1 : 0}
Agree. Did you have something like this in mind?

```jsx
interface CommonProps {
  //current component props
}

type DropZoneProps = 
  | { dropOnPage?: never; onClick?: never } & CommonProps
  | { dropOnPage: boolean; onClick: (event: React.MouseEvent<HTMLElement>) => void } & CommonProps;
```

2024-03-08 20:10 UTC, tatianau commented on polaris.shopify.com/content/components/selection-and-input/drop-zone.mdx
> +      accessibility and custom desight features.
Should this be design?
```suggestion
      accessibility and custom design features.
```

2024-03-08 20:10 UTC, tatianau commented on polaris-react/src/components/DropZone/DropZone.tsx
> +              tabIndex={onClick && dragAndDropOnly ? -1 : 0}
Can we add a test for `tabIndex` conditional value?

2024-03-11 18:40 UTC, chloerice reviewed
Hey Oksana, sorry for the delayed review! 

Just to recap the problem:
- DropZone supports onClick, but not onKeyUp, as focus intentionally moves directly to the file input
- Triggering a custom file picker instead of the native file dialog is currently not possible via keyboard interaction without the native file dialog also being triggered, since there is no way to prevent interaction with the DropZone input
- The proposed dragAndDropOnly prop will prevent keyboard navigation to the input, enabling implementation of a custom file picker triggered by click or by keypress of enter or space on an interactive child element

After digging into and fleshing out the story to understand the problem, I no longer think it's not necessary to require the DropZone.onClick since the interactive child could/should handle click, since it's actually interactive (see this suggested [updated story code](https://github.com/Shopify/polaris/pull/11713/files#r1520249364)) and the div configured by DropZone to handle click is not.

2024-03-11 18:40 UTC, chloerice commented on polaris.shopify.com/content/components/selection-and-input/drop-zone.mdx
> +This feature can be useful when DropZone implemented within confined space and the `children` property acts as the custom Modal trigger providing accessibility and custom design features.
```suggestion
When a small sized `DropZone` is configured with a child element that triggers a custom file picker, set `dragAndDropOnly` to prevent the file input from also triggering the native file dialog on keypress. 
```

2024-03-11 18:40 UTC, chloerice commented on polaris-react/src/components/DropZone/DropZone.tsx
> +  /** Determines if keyboard accessibility is enabled when using the component along with custom onClick */
```suggestion
  /** Whether or not keypress should trigger the native file picker. Use for small sized drop zones only when implementing a custom file picker, like the image picker triggered by variant thumbnails on the product details page. */
```

2024-03-11 18:40 UTC, chloerice commented on polaris.shopify.com/content/components/selection-and-input/drop-zone.mdx
> +      accessibility and custom desight features.
```suggestion
    title: With small size and custom file picker
    description: Use for small sized drop zones only when an interactive child triggers a custom file picker, like the image picker triggered by click or keypress of a product variant's thumbnail on the product details page.
```

2024-03-11 18:40 UTC, chloerice commented on polaris-react/src/components/DropZone/DropZone.tsx
> +  /** Determines if keyboard accessibility is enabled when using the component along with custom onClick */
Here is how to use TypeScript to require onClick be provided if dragAndDropOnly is true:

```tsx
interface BaseDropZoneProps {
  /** Label for the file input */
  label?: React.ReactNode;
  /** Adds an action to the label */
  labelAction?: LabelledProps['action'];
  /** Visually hide the label */
  labelHidden?: boolean;
  /** ID for file input */
  id?: string;
  /** Allowed file types */
  accept?: string;
  /**
   * Whether is a file or an image
   * @default 'file'
   */
  type?: DropZoneFileType;
  /** Sets an active state */
  active?: boolean;
  /** Sets an error state */
  error?: boolean;
  /**
   * Displays an outline border
   * @default true
   */
  outline?: boolean;
  /**
   * Displays an overlay on hover
   * @default true
   */
  overlay?: boolean;
  /** Text that appears in the overlay */
  overlayText?: string;
  /** Text that appears in the overlay when set in error state */
  errorOverlayText?: string;
  /**
   * Allows multiple files to be uploaded at once
   * @default true
   */
  allowMultiple?: boolean;
  /** Sets a disabled state */
  disabled?: boolean;
  /** The child elements to render in the dropzone. */
  children?: string | React.ReactNode;
  /** Allows a file to be dropped anywhere on the page */
  dropOnPage?: boolean;
  /** Whether or not keypress should trigger the native file picker. Use when `onClick` triggers a custom file picker, like the image picker on the product details page. */
  dragAndDropOnly?: boolean;
  /** Sets the default file dialog state */
  openFileDialog?: boolean;
  /** Allows child content to adjust height */
  variableHeight?: boolean;
  /** Adds custom validations */
  customValidator?(file: File): boolean;
  /** Callback triggered on click */
  onClick?(event: React.MouseEvent<HTMLElement>): void;
  /** Callback triggered on any file drop */
  onDrop?(files: File[], acceptedFiles: File[], rejectedFiles: File[]): void;
  /** Callback triggered when at least one of the files dropped was accepted */
  onDropAccepted?(acceptedFiles: File[]): void;
  /** Callback triggered when at least one of the files dropped was rejected */
  onDropRejected?(rejectedFiles: File[]): void;
  /** Callback triggered when one or more files are dragging over the drag area */
  onDragOver?(): void;
  /** Callback triggered when one or more files entered the drag area */
  onDragEnter?(): void;
  /** Callback triggered when one or more files left the drag area */
  onDragLeave?(): void;
  /** Callback triggered when the file dialog is canceled */
  onFileDialogClose?(): void;
}

interface DragAndDropOnlyProps {
  dragAndDropOnly: true;
  onClick(event: React.MouseEvent<HTMLElement>): void;
}

interface NoDragAndDropOnlyProps {
  dragAndDropOnly?: false;
  onClick?(event: React.MouseEvent<HTMLElement>): void;
}

export type DropZoneProps = BaseDropZoneProps &
  (DragAndDropOnlyProps | NoDragAndDropOnlyProps);
```

2024-03-11 18:40 UTC, chloerice commented on .changeset/hip-rockets-yawn.md
> +Added dragAndDropOnly property for DropZone to determine if keyboard accessibility is enabled when using the component along with custom onClick for files uploading
```suggestion
Added the `dragAndDropOnly` prop to `DropZone` to support prevention of navigation to the file input via keyboard or other assistive technologies. Use to prevent trigger of the native file dialog when an interactive child element triggers a custom file picker.
```

2024-03-11 18:40 UTC, chloerice commented on polaris-react/src/components/DropZone/DropZone.tsx
> +              tabIndex={onClick && dragAndDropOnly ? -1 : 0}
We need to prevent the input from being visible to screenreaders if it cannot be reached.

```suggestion
              aria-hidden={dragAndDropOnly ? true : undefined}
              tabIndex={onClick && dragAndDropOnly ? -1 : 0}
```

2024-03-11 18:40 UTC, chloerice commented on polaris-react/src/components/DropZone/DropZone.stories.tsx
> +}
```suggestion
export function SmallSizedWithCustomFilePicker() {
  const [activeModal, setActiveModal] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const [rejectedFiles, setRejectedFiles] = useState<File[]>([]);
  const hasError = rejectedFiles.length > 0;

  const handleThumbnailDrop = useCallback(
    (_droppedFiles: File[], acceptedFiles: File[], rejectedFiles: File[]) => {
      setFiles((files) => [...files, acceptedFiles[0]]);
      setRejectedFiles(rejectedFiles);
    },
    [],
  );

  const handleModalToggle = () => setActiveModal((activeModal) => !activeModal);

  const handleKeypress = (event: React.KeyboardEvent) => {
    event.stopPropagation();
    if (event.key === 'Enter' || event.key === 'Space') {
      handleModalToggle();
    }
  };

  const thumbnailStyle = {
    background: 'none',
    border: 'none',
    padding: 0,
    borderRadius: 'var(--p-border-radius-200)',
    outlineOffset: 'var(--p-border-width-050)',
    cursor: 'pointer',
    overflow: 'hidden',
    minHeight: '0',
    minWidth: '0',
    display: 'flex',
  };

  const fileUploadThumbnail = (
    <div style={{width: '40px', height: '40px'}}>
      <DropZone
        dragAndDropOnly
        error={hasError}
        allowMultiple={false}
        onClick={handleModalToggle}
        onDrop={handleThumbnailDrop}
      >
        <UnstyledButton style={thumbnailStyle} onKeyUp={handleKeypress}>
          <Thumbnail
            alt="Add variant image"
            size="small"
            source={ImageAddIcon}
          />
        </UnstyledButton>
      </DropZone>
    </div>
  );

  const uploadImageModal = !files.length ? (
    <div style={{height: '500px'}}>
      <Modal
        activator={fileUploadThumbnail}
        size="small"
        open={activeModal}
        onClose={handleModalToggle}
        title="Upload images from store gallery"
        primaryAction={{
          content: 'Save',
          onAction: handleModalToggle,
        }}
        secondaryActions={[
          {
            content: 'Cancel',
            onAction: handleModalToggle,
          },
        ]}
      >
        <Modal.Section>
          <ImageFileUpload />
        </Modal.Section>
      </Modal>
    </div>
  ) : null;

  return uploadImageModal;

  function ImageFileUpload() {
    const [files, setFiles] = useState<File[]>([]);
    const [rejectedFiles, setRejectedFiles] = useState<File[]>([]);
    const hasError = rejectedFiles.length > 0;

    const handleDrop = useCallback(
      (_droppedFiles, acceptedFiles, rejectedFiles) => {
        setFiles((files) => [...files, ...acceptedFiles]);
        setRejectedFiles(rejectedFiles);
      },
      [],
    );

    const fileUpload = !files.length && <DropZone.FileUpload />;
    const uploadedFiles = files.length > 0 && (
      <Box width="100%" padding="400">
        <BlockStack gap="400">
          {files.map((file, index) => (
            <InlineStack gap="400" align="start" key={index}>
              <Thumbnail
                size="small"
                alt={file.name}
                source={window.URL.createObjectURL(file)}
              />
              <div>
                {file.name}{' '}
                <Text variant="bodySm" as="p" tone="subdued">
                  {file.size} bytes
                </Text>
              </div>
            </InlineStack>
          ))}
        </BlockStack>
      </Box>
    );

    const errorMessage = hasError && (
      <Banner
        title="The following images couldn’t be uploaded:"
        tone="critical"
      >
        <List type="bullet">
          {rejectedFiles.map((file, index) => (
            <List.Item key={index}>
              {`"${file.name}" is not supported. File type must be .gif, .jpg, .png or .svg.`}
            </List.Item>
          ))}
        </List>
      </Banner>
    );

    return (
      <BlockStack gap="400" inlineAlign="stretch" align="center">
        {errorMessage}
        <DropZone accept="image/*" type="image" onDrop={handleDrop}>
          {uploadedFiles}
          {fileUpload}
        </DropZone>
      </BlockStack>
    );
  }
}
```

2024-03-11 18:40 UTC, chloerice commented on polaris.shopify.com/pages/examples/drop-zone-drag-and-drop-only.tsx
> +export default withPolarisExample(WithCustomModalAndDragAndDropOnlyExample);
```suggestion
function SmallSizedWithCustomFilePickerExample() {
  const [activeModal, setActiveModal] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const [rejectedFiles, setRejectedFiles] = useState<File[]>([]);
  const hasError = rejectedFiles.length > 0;

  const handleThumbnailDrop = useCallback(
    (_droppedFiles: File[], acceptedFiles: File[], rejectedFiles: File[]) => {
      setFiles((files) => [...files, acceptedFiles[0]]);
      setRejectedFiles(rejectedFiles);
    },
    [],
  );

  const handleModalToggle = () => setActiveModal((activeModal) => !activeModal);

  const handleKeypress = (event: React.KeyboardEvent) => {
    event.stopPropagation();
    if (event.key === 'Enter' || event.key === 'Space') {
      handleModalToggle();
    }
  };

  const thumbnailStyle = {
    background: 'none',
    border: 'none',
    padding: 0,
    borderRadius: 'var(--p-border-radius-200)',
    outlineOffset: 'var(--p-border-width-050)',
    cursor: 'pointer',
    overflow: 'hidden',
    minHeight: '0',
    minWidth: '0',
    display: 'flex',
  };

  const fileUploadThumbnail = (
    <div style={{width: '40px', height: '40px'}}>
      <DropZone
        dragAndDropOnly
        error={hasError}
        allowMultiple={false}
        onClick={handleModalToggle}
        onDrop={handleThumbnailDrop}
      >
        <UnstyledButton style={thumbnailStyle} onKeyUp={handleKeypress}>
          <Thumbnail
            alt="Add variant image"
            size="small"
            source={ImageAddIcon}
          />
        </UnstyledButton>
      </DropZone>
    </div>
  );

  const uploadImageModal = !files.length ? (
    <div style={{height: '500px'}}>
      <Modal
        activator={fileUploadThumbnail}
        size="small"
        open={activeModal}
        onClose={handleModalToggle}
        title="Upload images from store gallery"
        primaryAction={{
          content: 'Save',
          onAction: handleModalToggle,
        }}
        secondaryActions={[
          {
            content: 'Cancel',
            onAction: handleModalToggle,
          },
        ]}
      >
        <Modal.Section>
          <ImageFileUpload />
        </Modal.Section>
      </Modal>
    </div>
  ) : null;

  return uploadImageModal;

  function ImageFileUpload() {
    const [files, setFiles] = useState<File[]>([]);
    const [rejectedFiles, setRejectedFiles] = useState<File[]>([]);
    const hasError = rejectedFiles.length > 0;

    const handleDrop = useCallback(
      (_droppedFiles, acceptedFiles, rejectedFiles) => {
        setFiles((files) => [...files, ...acceptedFiles]);
        setRejectedFiles(rejectedFiles);
      },
      [],
    );

    const fileUpload = !files.length && <DropZone.FileUpload />;
    const uploadedFiles = files.length > 0 && (
      <Box width="100%" padding="400">
        <BlockStack gap="400">
          {files.map((file, index) => (
            <InlineStack gap="400" align="start" key={index}>
              <Thumbnail
                size="small"
                alt={file.name}
                source={window.URL.createObjectURL(file)}
              />
              <div>
                {file.name}{' '}
                <Text variant="bodySm" as="p" tone="subdued">
                  {file.size} bytes
                </Text>
              </div>
            </InlineStack>
          ))}
        </BlockStack>
      </Box>
    );

    const errorMessage = hasError && (
      <Banner
        title="The following images couldn’t be uploaded:"
        tone="critical"
      >
        <List type="bullet">
          {rejectedFiles.map((file, index) => (
            <List.Item key={index}>
              {`"${file.name}" is not supported. File type must be .gif, .jpg, .png or .svg.`}
            </List.Item>
          ))}
        </List>
      </Banner>
    );

    return (
      <BlockStack gap="400" inlineAlign="stretch" align="center">
        {errorMessage}
        <DropZone accept="image/*" type="image" onDrop={handleDrop}>
          {uploadedFiles}
          {fileUpload}
        </DropZone>
      </BlockStack>
    );
  }
}

export default withPolarisExample(SmallSizedWithCustomFilePickerExample);
```

2024-11-16 03:38 UTC, closed without merging