[Pagination] Add accessibility labels prop
Shopify/polaris-react pull request #3667
Opened 2020-11-30 20:18 UTC by ashwinnarayanan2001

### WHY are these changes introduced? ### WHAT is this pull request doing?
This pull request fixes Shopify/polaris-ux#457. It adds an 'accessibilityLabels' prop to the Pagination component. This prop is responsible for providing custom accessibility labels (aria-labels) for the previous and next button and UnstyledLink components. 

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

2020-12-16 18:53 UTC, kyledurand commented on src/components/Pagination/tests/Pagination.test.tsx
> +    });
Looks like we need a test for the default labels on `UnstyledLink` as well

2020-12-16 19:10 UTC, kyledurand commented on src/components/Pagination/tests/Pagination.test.tsx
> +    });
I've added the test and rebased

2020-12-16 19:10 UTC, kyledurand approved these changes

2020-12-18 23:38 UTC, alex-page approved these changes

2020-12-18 23:38 UTC, alex-page commented
I am a little worried that people will not use this prop. Should we make it required?

2020-12-21 15:55 UTC, alex-page requested changes
I am a little worried that people will not use this prop. Should we make it required and add it to version 6? @kyledurand @ashwinnarayanan2001 any thoughts?

2021-01-07 18:50 UTC, kyledurand commented
What about adding it to v5 and making an issue to make them non optional in v6?

2021-01-07 18:50 UTC, merged