[SkeletonPage] Remove new DL fallbacks
Shopify/polaris-react pull request #3791
Opened 2021-01-07 17:53 UTC by kyledurand

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-ux/issues/541

### WHAT is this pull request doing?

Removes new design language fallbacks
Keep in mind that changes still need to be made to page and card so there will be a few margins that are off when comparing to what's in heroku

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

2021-01-07 18:47 UTC, aveline requested changes
The component changes look good to me, but looks like there are some tests that still need updating

2021-01-07 20:53 UTC, kyledurand commented
Looks like the v6 branch is broken due to pagination tests. This can wait for a review until then

2021-01-08 15:22 UTC, alex-page approved these changes

2021-01-08 16:34 UTC, aveline approved these changes

2021-01-08 16:34 UTC, merged