Migrate content changes from `polaris-react/**/README.md` files to polaris.shopify.com
Shopify/polaris-react pull request #6679
Opened 2022-07-20 01:15 UTC by alex-page

- [x] Add missing content
- [x] Enforce reviews for `README.md` files

2022-07-20 07:08 UTC, martenbjork requested changes

2022-07-20 07:08 UTC, martenbjork commented on polaris.shopify.com/content/components/modal.md
> +- Close when merchants press the `X` button, the `Cancel` button, the <kbd>Esc</kbd> key, or when merchants click or tap the area outside the modal.
Nice one!

2022-07-20 07:08 UTC, martenbjork commented on polaris.shopify.com/content/foundations/patterns/error-messages.md
> -
This stuff looks broken. It only renders this:

> on the field to indicate validation progress.

2022-07-20 14:18 UTC, alex-page commented on polaris.shopify.com/content/foundations/patterns/error-messages.md
> -
Yep. Fixed this up. Silly vscode.

2022-07-21 02:07 UTC, alex-page commented on polaris-react/src/components/ChoiceList/README.md
> +
```suggestion
```

2022-07-21 02:07 UTC, alex-page commented on polaris-react/src/components/ChoiceList/README.md
> +- Option b
```suggestion
If the customer abandons their checkout, send them an email reminder to complete their order
```

2022-07-21 15:28 UTC, merged