[polaris.shopify.com] Update IA and navigation
Shopify/polaris-react pull request #7232
Opened 2022-09-20 13:10 UTC by martenbjork

This PR Introduces a new IA for the Polaris website 🚀

Closes #7294
Closes #6417
Closes #6657
Closes #6705

https://user-images.githubusercontent.com/875708/192775921-5d26b714-fe19-465a-97f2-6d6fc8b448ec.mp4

This PR adds support for the new IA that JJ has championed. To accommodate the new IA, I had to rip out a ton of stuff and touch up the design.

The PR is quite big — sorry about that — but most of it is moved markdown files and deleted stuff. On the whole, this PR reduces the total lines of code.

✅ Added a new side nav, built on @gui-santos awesome work on the mobile nav.
✅ Removed `MobileNav`. It's part of the Frame component now.
✅ Combined `FoundationsGrid` and `ComponentsGrid` into `Grid`.
✅ Renamed `Layout` to `Page` to clarify what it does
✅ Removed a bunch of redundant `getStaticProps` by using a catch-all template that automatically deals with most pages.
✅ Simplified the script that generates nav.json. Removed all hard coded nav items.

2022-09-28 13:53 UTC, kyledurand commented
https://user-images.githubusercontent.com/6844391/192796976-e4cff537-97e3-4ece-a2ad-d1c349d14b9e.mp4

Is there some weirdness going on with +/- and active states here?

2022-09-28 15:14 UTC, johanstromqvist commented
In the demo, navigating to a child (about polaris) of a collapsed parent (foundations) doesn't expand and show the current location in the nav. Is that intentional?

2022-09-28 16:41 UTC, gui-santos requested changes
Wow! Amazing work and a lot of changes
but I think the website will improve a lot

I got a couple of suggestions and questions, nothing too important though 🙏

2022-09-28 16:41 UTC, gui-santos commented on polaris.shopify.com/package.json
> +    "framer-motion": "^6.5.1",
😍

2022-09-28 16:41 UTC, gui-santos commented on polaris.shopify.com/pages/[...slug].tsx
> +  }/index.md`;
Does this have a chance of returning `content//index.md`?

2022-09-28 16:41 UTC, gui-santos commented on polaris.shopify.com/pages/[...slug].tsx
> +}
Just a small suggestion, maybe we could create a "catchAllTemplateExcludeList" and then every time we create a new page that shouldn't be rendered with CatchAllTemplate we just include the path in the array

```suggestion
const catchAllTemplateExcludeList = [
  '/whats-new',
  '/icons',
  '/foundations',
  '/design',
  '/content',
  '/patterns',
  '/tokens'
]

function fileShouldNotBeRenderedWithCatchAllTemplate(path: string): boolean {
  return (
    !path.startsWith('/components') &&
    !catchAllTemplateExcludeList.includes(path)
  );
}
```

Not a blocker though, the code already works like this :)

2022-09-28 16:41 UTC, gui-santos commented on polaris.shopify.com/src/components/Breadcrumbs/Breadcrumbs.tsx
> +function Breadcrumbs({}: Props) {
I guess we can remove this if there are no Props, no?

```suggestion
function Breadcrumbs() {
```

2022-09-28 16:41 UTC, gui-santos commented on polaris.shopify.com/src/components/Breadcrumbs/Breadcrumbs.tsx
> +  let segments: {url: string; text: string}[] = [
```suggestion
  const segments: {url: string; text: string}[] = [
```

I think this can be const because we are not reassigning a value to it
The `.push` in line 35 is ok, it doesn't create a new array

2022-09-29 08:38 UTC, martenbjork commented
> In the demo, navigating to a child (about polaris) of a collapsed parent (foundations) doesn't expand and show the current location in the nav. Is that intentional?

Nice catch, @johanstromqvist! 🔥 I was too focused on nav clicks, and didn't consider non-nav navigation... Fixed!

https://user-images.githubusercontent.com/875708/192983186-e7715157-1a87-48e9-8c50-63389b324679.mov

2022-09-29 08:42 UTC, martenbjork commented on polaris.shopify.com/package.json
> +    "framer-motion": "^6.5.1",
🥰

2022-09-29 08:50 UTC, martenbjork commented on polaris.shopify.com/pages/[...slug].tsx
> +  }/index.md`;
Yes 😄 I added a stricter check for this so it will throw a proper error if the slug is undefined (which, I think, should be impossible).

2022-09-29 09:34 UTC, martenbjork commented
@gui-santos Thanks for all the great suggestions! 💯🔥 I committed them all!

> Is there some weirdness going on with +/- and active states here?

@kyledurand I can't reproduce the weirdness you're seeing, but regardless, I reworked the logic so it might be worth having a look again! 

One thing to note is that this logic is based on Next router's `asPath` value which is a little delayed when using `yarn dev`. So `yarn start` should be snappier in case you want to get a feel for how it will actually work when in production.

2022-09-29 13:16 UTC, gui-santos approved these changes
Again, this looks great! I loved this change 🖤

2022-09-29 13:20 UTC, gui-santos commented on polaris.shopify.com/pages/whats-new.tsx
> +          </>
Sorry, one last thing:

<img width="799" alt="Screenshot 2022-09-29 at 15 17 16" src="https://user-images.githubusercontent.com/6597467/193042000-81a53398-979d-43a9-8c50-4bed1e318c57.png">

Maybe it's possible to put a "key" in a fragment, I'm not sure, but try it. Maybe you will need to do `<React.Fragment key={title}>`

I hope it works with key because adding a wrapping element here may screw your layout

Another alternative would be making this a React component and them you put the key when using that component inside this map

2022-09-29 13:46 UTC, martenbjork commented on polaris.shopify.com/pages/whats-new.tsx
> +          </>
Nice catch! I added a bit of layout to the page, which removed the need for a Fragment all-together. The post wrappers now have `key` attributes! 🙌

2022-09-29 15:00 UTC, merged