[SkeletonPage] Rebuild with layout primitives
Shopify/polaris-react pull request #7797
Opened 2022-11-23 21:31 UTC by chazdean

### WHY are these changes introduced?

Fixes [#7714](https://github.com/Shopify/polaris/issues/7714)

### WHAT is this pull request doing?

- Refactors `SkeletonPage` and its child components to use our layout primitives.
- Removes `max-width: 100%` property from AlphaStack
- Adds storybook examples for `SkeletonPage` with `narrowWidth` and with `fullWidth` props

#### Issues with current PR:

   <details>
      <summary>Unable to center `SkeletonPage` when `narrowWidth` prop is used - SOLVED ✅</summary>
<table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td> <img width="400" alt="Screenshot 2022-11-24 at 9 13 21 AM" src="https://user-images.githubusercontent.com/59836805/203805854-4748a46a-8208-476e-9c16-d0071e4ff66b.png"> </td>
<td> <img width="400" alt="Screenshot 2022-11-24 at 9 10 25 AM" src="https://user-images.githubusercontent.com/59836805/203806188-bd5cde58-0787-46f1-a2b3-cbaf2a228d52.png"> </td>
</tr>
<tr>
<td> <img width="400" alt="Screenshot 2022-11-24 at 9 13 42 AM" src="https://user-images.githubusercontent.com/59836805/203806392-466df6a0-29ee-4d06-bc40-523b60b97853.png"> </td>
<td> <img width="400" alt="Screenshot 2022-11-24 at 9 11 17 AM" src="https://user-images.githubusercontent.com/59836805/203806492-6793f6a3-591a-4cb4-9f13-46da44f64dfe.png"> </td>
</tr>
</table>
    </details>

<details>
      <summary>Our current `Text` component has the opposite breakpoint behaviour compared to how `.Title` is used in `SkeletonPage` - SOLVED ✅</summary>
      <table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td> <img width="400" alt="before text" src="https://user-images.githubusercontent.com/59836805/203808391-3f3bd9d2-421e-4e09-a843-e579b936d39f.gif"> </td>
<td> <img width="400" alt="before text" src="https://user-images.githubusercontent.com/59836805/203808879-55e311ef-708b-44c9-a28e-4582c77d0992.gif"> </td>
</tr>
<tr>
<td> 

```java
.Title {
  font-weight: var(--p-font-weight-semibold);
  font-size: 24px;
  line-height: 28px;

  @media #{$p-breakpoints-md-up} {
    font-size: 20px;
  }
}
```

 </td>
<td>
    
```java
.headingXl {
  font-size: var(--p-font-size-300);
  line-height: var(--p-font-line-height-3);

  @media #{$p-breakpoints-md-up} {
    font-size: var(--p-font-size-400);
    line-height: var(--p-font-line-height-4);
  }
}
```
    
</td>
</tr>
</table>
    </details>

~~`role` prop is missing from `Box`, creating a separate issue to solve this [here](https://github.com/Shopify/polaris/pull/7799)~~ SOLVED ✅

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-11-24 18:35 UTC, aveline commented
@chaz I created a codepen of how we should be able to use flex to center when `narrowWidth` is set

https://codepen.io/enileva/pen/xxzjOej

then I tried it with the component by wrapping the outer `Box` with this `div`

`<div style={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>`

which worked

![localhost_6006__path=_story_all-components-skeletonpage--with-narrow-width](https://user-images.githubusercontent.com/3474483/203848524-d68c1d3e-5ea2-4d5e-a3ad-d9046656ef50.png)

but as we know, using `AlphaStack` doesn't. And then I realized it's because of the child `AlphaStack` with the `fullWidth`, the styles are getting mixed up with the parent `AlphaStack` that we don't want to be `fullWidth`. So that's a problematic implementation with `fullWidth` that we should revisit. Any thoughts @kyledurand?

Let's try to figure out if we can fix `AlphaStack` but if that drags on, we can unblock this by shipping it with the div and inline styles above?

2022-11-25 17:47 UTC, aveline commented
I looked at `AlphaStack` and this is the issue

https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/AlphaStack/AlphaStack.scss#L30

It's overriding the `max-width` on `Box`. So not related to `fullWidth` like I originally thought.

@laurkim @kyledurand any context on why we added `max-width: 100%;` to `AlphaStack`? Would it be safe to remove?

2022-11-25 19:16 UTC, kyledurand commented
> any context on why we added max-width: 100%; to AlphaStack? Would it be safe to remove?

Might have something to do with the `> * {width: 100%}` for fullWidth below. I think maybe it was causing overflow on the container unless max width was applied but I'm speculating. Lo would know when she's back.

For now, as an unblocker, we could remove the max width and do:

```scss
.fullWidth {
  > * {
    flex: 1 1 auto;
  }
}
```

And see if that causes any visual regressions. We shouldn't need to use width on a flex container these days.

**OR**

Try removing the fullWidth prop because I'm not sure it's used anywhere and it's kind of misleading. The flex container should take the full width anyway and messing with the ~~children~~ direct descendants in this way feels weird 
![image](https://media.tenor.com/-YFzV9_ef2YAAAAC/archer-phrasing.gif)

2022-11-28 13:24 UTC, laurkim commented
> It's overriding the `max-width` on `Box`. So not related to `fullWidth` like I originally thought.
> 
> @laurkim @kyledurand any context on why we added `max-width: 100%;` to `AlphaStack`? Would it be safe to remove?

@aveline @kyledurand I think it was added to fix a bug on content when the `fullWidth` prop was passed in during the early stages of build. Should be safe to remove.

@chazdean can we add separate storybook examples for SkeletonPage with `narrowWidth` and with `fullWidth` props?

2022-11-28 16:50 UTC, laurkim commented on .changeset/strong-bottles-swim.md
> +Added `narrowWidth` and `fullWidth` examples to AlphaStack stories
```suggestion
'@shopify/polaris': minor
---

Refactored `SkeletonPage` to use primitive Layout components
Removed `max-width` on children in `AlphaStack`
Added `narrowWidth` and `fullWidth` examples to `AlphaStack` stories
```

2022-11-28 17:03 UTC, sarahill commented
> Our current `Text` component has the opposite breakpoint behaviour compared to how `.Title` is used in `SkeletonPage`

Yea, this is one I expected we'd have to manually set as it does behave differently. Expected behavior: Page title remains `20px` across breakpoints.

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/8629173/204337345-dce2d1b4-b13b-4a6e-970b-9c73e4fb7833.png">

2022-11-29 22:21 UTC, sarahill approved these changes
✅

2022-11-30 13:09 UTC, kyledurand commented on polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
> +          maxWidth: '662px',
I think these should be moved to the scss file. If we do something like:

```scss
--pc-skeleton-page-max-width: 998px;
--pc-skeleton-page-max-width-narrow: 662px;
```
Then the px values get converted to rem with post css.

Then you can just pass in `var(--pc-skeleton-page-max-width), var(--pc-skeleton-page-max-width-narrow)` as the props

2022-12-02 14:49 UTC, laurkim requested changes, later dismissed
I recommend decoupling the new full width and narrow width stories from this PR.
I tested the existing SkeletonPage without any of the layout primitive changes off latest main with those new stories added and I'm seeing a difference for the `withFullWidth` stories. Here's a gif comparing the chromatic from this PR and me running latest main with the story locally.

![skeletonpage](https://user-images.githubusercontent.com/26749317/205319463-0db3b9c2-8d26-488a-b301-b7b6df7c456b.gif)

Also, looks like this is exceeding size limit. Can we bump to the threshold to 220 kb?

2022-12-02 15:41 UTC, aveline approved these changes

2022-12-02 15:49 UTC, laurkim approved these changes
Tophatted stories at all breakpoints against latest main running locally and lgtm! Nice 💯

2022-12-02 16:42 UTC, merged