Patterns MVP
Shopify/polaris-react pull request #7843
Opened 2022-12-06 04:02 UTC by gwyneplaine

## Reboot Pattern Guidance
See [Reboot Polaris patterns vault project](https://vault.shopify.io/gsd/projects/30559)

- New layout primitives `Stack`, `Box`, `Grid`, `Row`.
- Playroom patched to support larger code snippets.
- New designs and content for the [patterns](https://polaris.shopify.com/patterns) pages.
- Deprecated old patterns:
  ||Old|New|
  |--|--|--|
  |**design-patterns** | `/patterns/design-patterns` | `404`|
  |**page-layouts** | `/patterns/page-layouts` | `404`|
  |**error-messages** | `/patterns/error-messages` | `/content/error-messages`|
  |**help-content** | `/patterns/help-content` | `/content/help-content`|
  |**loading** | `/patterns/loading` | `/patterns-legacy/loading`|
  |**new-badge** | `/patterns/new-badge` | `/patterns-legacy/new-badge`|
  |**pickers** | `/patterns/pickers` | `/patterns-legacy/pickers`|
  |**text-fields** | `/patterns/text-fields` | `/patterns-legacy/text-fields`|
- Page padding and max-width adjusted such that live previews for components and patterns always display the desktop breakpoint.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

2022-12-14 08:14 UTC, gwyneplaine commented
/stageit

2022-12-15 00:23 UTC, jesstelford commented
/stageit

2022-12-15 01:12 UTC, jesstelford commented
/stageit

2022-12-15 02:12 UTC, jesstelford commented
/stageit

2022-12-15 02:39 UTC, jesstelford commented
/stageit

2022-12-15 03:03 UTC, jesstelford commented
/stageit

2022-12-15 05:31 UTC, jesstelford commented
/stageit

2022-12-15 06:03 UTC, jesstelford commented
/stageit

2022-12-15 06:23 UTC, jesstelford commented
/stageit

2022-12-15 06:43 UTC, jesstelford commented
/stageit

2022-12-15 06:53 UTC, jesstelford commented
/stageit

2022-12-15 07:02 UTC, jesstelford commented
/stageit

2022-12-15 08:16 UTC, jesstelford commented
/stageit

2022-12-23 02:10 UTC, jesstelford commented
/stageit

2022-12-23 02:45 UTC, jesstelford commented
/stageit

2023-01-20 04:04 UTC, gwyneplaine commented
/stageit

2023-01-26 22:25 UTC, gwyneplaine commented
/stageit

2023-01-26 22:42 UTC, gwyneplaine commented
/stageit

2023-01-26 23:06 UTC, gwyneplaine commented
/stageit

2023-01-26 23:19 UTC, gwyneplaine commented
/stageit

2023-01-26 23:35 UTC, gwyneplaine commented
/stageit

2023-01-26 23:46 UTC, gwyneplaine commented
/stageit

2023-02-01 04:40 UTC, gwyneplaine commented
/stageit

2023-02-01 05:48 UTC, gwyneplaine commented
/stageit

2023-02-01 23:22 UTC, gwyneplaine commented
/stageit

2023-02-13 03:48 UTC, gwyneplaine commented
/stageit

2023-02-13 04:25 UTC, gwyneplaine commented
/stageit

2023-02-13 22:09 UTC, gwyneplaine commented
/stageit

2023-02-15 03:47 UTC, gwyneplaine commented
/stageit

2023-02-15 05:59 UTC, gwyneplaine commented
/stageit

2023-02-15 06:18 UTC, gwyneplaine commented
/stageit

2023-02-16 06:15 UTC, gwyneplaine commented
/stageit

2023-02-16 06:48 UTC, gwyneplaine commented
/stageit

2023-02-16 23:30 UTC, gwyneplaine commented
/stageit

2023-02-21 22:17 UTC, gwyneplaine commented
/stageit

2023-02-22 04:12 UTC, jesstelford requested changes
Pairing with @gwyneplaine

2023-02-22 04:12 UTC, jesstelford commented on patches/playroom+0.28.0.patch
> ++        console.log(e);
```suggestion
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/content/components/layout-and-structure/page.md
> +- [Resource Details](/patterns/resource-details)
```suggestion
- [App settings layout](/patterns/app-settings-layout)
- [Resource details layout](/patterns/resource-details-layout)
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/content/components/selection-and-input/date-picker.md
> +- [Date Picking](/patterns/date-picking)
```suggestion
- [Date picking](/patterns/date-picking)
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/src/components/PatternsPage/index.tsx
> +              to make it better. [See old patterns here]("/patterns-legacy").`}
```suggestion
              to make it better. [See old patterns here](/patterns-legacy).`}
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/content/patterns-legacy/new-badge.md
> +![Card with the new badge aligned to the right of the card heading](/images/foundations/patterns-legacy/new-badge/new-badge@2x.png)
```suggestion
![Card with the new badge aligned to the right of the card heading](/images/foundations/patterns/new-badge/new-badge@2x.png)
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/content/patterns-legacy/text-fields.md
> +  message: This pattern is no longer supported.
```suggestion
noIndex: true
status:
  value: Deprecated
  message: This pattern is no longer supported.
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/src/components/PatternThumbnail/PatternThumbnail.tsx
> +function ComponentThumbnail({title, img}: Props) {
```suggestion
function PatternThumbnail({title, img}: Props) {
```

2023-02-22 04:12 UTC, jesstelford commented on polaris.shopify.com/src/components/PatternThumbnail/PatternThumbnail.tsx
> +export default ComponentThumbnail;
```suggestion
export default PatternThumbnail;
```

2023-02-22 05:43 UTC, gwyneplaine commented on polaris.shopify.com/src/components/Grid/Grid.tsx
> +          <p>{stripMarkdownLinks(description || '')}</p>
Why do we need this? Ideally this should not render a p tag if no description exists.

2023-02-22 05:48 UTC, jesstelford approved these changes

2023-02-22 22:32 UTC, gwyneplaine commented
/stageit

2023-02-22 23:51 UTC, gwyneplaine commented
/stageit

2023-02-23 00:56 UTC, gwyneplaine commented
/stageit

2023-02-23 02:19 UTC, merged