Update `plain` font size
Shopify/polaris-react pull request #9504
Opened 2023-06-21 20:12 UTC by aveline

### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-summer-editions/issues/537

### WHAT is this pull request doing?

Updates the font size on `plain` buttons to `100`

### How to 🎩

Review in [Storybook](https://5d559397bae39100201eedc1-fdppmlisyl.chromatic.com/?path=/story/all-components-button--all&globals=polarisSummerEditions2023:true) and verify `plain` buttons font size is larger than all other buttons when behind beta flag.

2023-06-21 23:31 UTC, aaronccasanova approved these changes

2023-06-21 23:39 UTC, sarahill requested changes
font-size should be `13px` with `20px` line-height or the `bodyMd` `Text` variant with a `medium` weight to match the default text size/height.

2023-06-22 18:59 UTC, sarahill approved these changes
Still seeing the `14px` in storybook but the tokens look correct so it should be good 👍

2023-06-22 20:41 UTC, aveline commented
Oh looks like the Storybook link changed. This is the newer one https://5d559397bae39100201eedc1-cvhfopgdfk.chromatic.com/?path=/story/all-components-button--all&globals=polarisSummerEditions2023:true

Confirmed it has the correct font size.

2023-06-22 20:41 UTC, merged