[IndexFilters] Add peekQueryField prop to show mini search field next to filter activator button.
Shopify/polaris-react pull request #9853
Opened 2023-07-28 11:47 UTC by jesstelford

- [View the Hack Days project](https://hackdays.shopify.io/projects/17097)
- [Try it in Storybook](https://5d559397bae39100201eedc1-epqlfalcmp.chromatic.com/?path=/story/all-components-indexfilters--with-query-visibility-options&globals=polarisSummerEditions2023:true)
- [Give it a ✅](https://github.com/Shopify/polaris/pull/9853/files#submit-review)

---

![peek-search-demo](https://github.com/Shopify/polaris/assets/612020/bddf709a-347c-45b2-85eb-0b3edf88fab5)

## The problem

Merchants are asking to bring back search on the Product & Orders tables.

But... It's already there, and always has been!

## The hypothesis

The search icon/button is non-obvious & merchants want an obvious search field they can click into to start searching.

## The solution

A mini-search bar which acts identically to the existing search icon - clicking it shows the full search bar.

Enable it with `<IndexFilters peekQueryField>`.

Below `md` screen width, it will revert to the search icon to save space.

It even works with pre-uplift designs!

![peek-search-md](https://github.com/Shopify/polaris/assets/612020/2862de65-7223-45ee-bab8-f6f948ea98b3)

<details>
<summary>Screenshots</summary>

![peek-query-uplift-md](https://github.com/Shopify/polaris/assets/612020/0b70f5aa-efc9-4056-b972-a79c2810ea42)
![peek-query-uplift-sm](https://github.com/Shopify/polaris/assets/612020/2cde97ae-5fa5-456c-9d78-4e20b03eff85)

</details>

<details>
<summary>Screenshots (pre-uplift)</summary>

![peek-query-old-md](https://github.com/Shopify/polaris/assets/612020/628e5067-9eb7-4cdb-aa16-8c01eac930c3)
![peek-query-old-sm](https://github.com/Shopify/polaris/assets/612020/fd5f2f5d-f259-4bab-9857-80b5e90a2c42)

</details>

2023-07-28 13:55 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/IndexFilters.scss
> +  flex-basis: 0;
Shrinks the area surrounding the icon buttons (including the new search field) to take as little space as possible. Necessitates the later `wrap={false}`

2023-07-28 13:56 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/IndexFilters.tsx
> +      Never<SearchFilterButtonPropsHiddenQuery>);
Mutually exclusive props (can't have `peekQueryField` and `hideQueryField` be booleans at the same time)

2023-07-28 13:56 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/IndexFilters.tsx
> +                                : {peekQueryField})}
Makes TypeScript happy.

2023-07-28 13:56 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.scss
> +    max-width: 7rem;
This is the search field.

2023-07-28 13:58 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.scss
> +    min-width: 5em;
Otherwise the earlier `flex-basis: 0` causes the text field to be 10px wide 😓

2023-07-28 13:59 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx
> +          peekQueryField && styles.PeekQueryField,
Made the show/hide logic be in CSS so we can take advantage of media queries (peek reverts to an icon at sm and below).

2023-07-28 13:59 UTC, jesstelford commented on polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx
> +          onFocus={onClick}
L33t h@ckZ!

2023-07-28 14:00 UTC, jesstelford commented on polaris-react/src/types.ts
> + *   | ((MessageBasics & WithAttachment) & Never<WithText>);
The example was wrong here, so I fixed it.

2023-07-28 14:00 UTC, jesstelford commented on polaris-react/src/types.ts
> +  : T;
¯\_(ツ)_/¯ Wanna keep it? I've used it a few times recently - great for debugging the final concrete type in your IDE (just wrap the exported type in `ExpandRecursively` then hover your mouse / look at the definition).

2023-07-28 16:48 UTC, sam-b-rose approved these changes

2023-07-28 16:48 UTC, sam-b-rose commented on polaris-react/src/types.ts
> +  : T;
Very nice, I say we keep it!

2023-07-28 16:48 UTC, sam-b-rose commented on polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.scss
> +  flex-direction: row;
Just one alignment suggestion!

```suggestion
  flex-direction: row;
  align-items: center; 
```

| Before | After |
| --- | --- |
|  <img width="120" alt="before" src="https://github.com/Shopify/polaris/assets/11774595/f9e2f9aa-8026-4870-8804-71ecf74266dd"> | <img width="110" alt="after" src="https://github.com/Shopify/polaris/assets/11774595/dad8b0ca-0434-4593-b80d-b99bbba14e46"> |

2023-07-31 14:26 UTC, ouellettejordan requested changes
This has been litigated many times over, many alternatives explored, and the decision was to leave this experience as-is. We could reconsider with this solution, but I'm not sure we want to open this can of worms again.

There is a lot of history here and too much to cover in this context. Please DM if there are further concerns.

2023-09-21 01:10 UTC, closed without merging